sudo: required
services:
  - docker

before_install:
  - docker build -t captainfurious/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true captainfurious/docker-react npm run test

deploy:
  provider: heroku
  api_key: "113da859-4b3f-4234-b058-e9615f5422d1"
  app: "docker-test437"